/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSetoranRouteImport } from './routes/_authenticated/setoran'
import { Route as AuthenticatedSantriRouteImport } from './routes/_authenticated/santri'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSantriIdRouteImport } from './routes/_authenticated/santri.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSetoranRoute = AuthenticatedSetoranRouteImport.update({
  id: '/setoran',
  path: '/setoran',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSantriRoute = AuthenticatedSantriRouteImport.update({
  id: '/santri',
  path: '/santri',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSantriIdRoute = AuthenticatedSantriIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSantriRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/santri': typeof AuthenticatedSantriRouteWithChildren
  '/setoran': typeof AuthenticatedSetoranRoute
  '/santri/$id': typeof AuthenticatedSantriIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/santri': typeof AuthenticatedSantriRouteWithChildren
  '/setoran': typeof AuthenticatedSetoranRoute
  '/santri/$id': typeof AuthenticatedSantriIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/santri': typeof AuthenticatedSantriRouteWithChildren
  '/_authenticated/setoran': typeof AuthenticatedSetoranRoute
  '/_authenticated/santri/$id': typeof AuthenticatedSantriIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/santri'
    | '/setoran'
    | '/santri/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/dashboard' | '/santri' | '/setoran' | '/santri/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/santri'
    | '/_authenticated/setoran'
    | '/_authenticated/santri/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/setoran': {
      id: '/_authenticated/setoran'
      path: '/setoran'
      fullPath: '/setoran'
      preLoaderRoute: typeof AuthenticatedSetoranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/santri': {
      id: '/_authenticated/santri'
      path: '/santri'
      fullPath: '/santri'
      preLoaderRoute: typeof AuthenticatedSantriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/santri/$id': {
      id: '/_authenticated/santri/$id'
      path: '/$id'
      fullPath: '/santri/$id'
      preLoaderRoute: typeof AuthenticatedSantriIdRouteImport
      parentRoute: typeof AuthenticatedSantriRoute
    }
  }
}

interface AuthenticatedSantriRouteChildren {
  AuthenticatedSantriIdRoute: typeof AuthenticatedSantriIdRoute
}

const AuthenticatedSantriRouteChildren: AuthenticatedSantriRouteChildren = {
  AuthenticatedSantriIdRoute: AuthenticatedSantriIdRoute,
}

const AuthenticatedSantriRouteWithChildren =
  AuthenticatedSantriRoute._addFileChildren(AuthenticatedSantriRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSantriRoute: typeof AuthenticatedSantriRouteWithChildren
  AuthenticatedSetoranRoute: typeof AuthenticatedSetoranRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSantriRoute: AuthenticatedSantriRouteWithChildren,
  AuthenticatedSetoranRoute: AuthenticatedSetoranRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
