/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUjianRouteImport } from './routes/_authenticated/ujian'
import { Route as AuthenticatedTasmiRouteImport } from './routes/_authenticated/tasmi'
import { Route as AuthenticatedSetoranRouteImport } from './routes/_authenticated/setoran'
import { Route as AuthenticatedSantriRouteImport } from './routes/_authenticated/santri'
import { Route as AuthenticatedPengaturanRouteImport } from './routes/_authenticated/pengaturan'
import { Route as AuthenticatedLaporanHarianRouteImport } from './routes/_authenticated/laporan-harian'
import { Route as AuthenticatedLaporanRouteImport } from './routes/_authenticated/laporan'
import { Route as AuthenticatedHalaqohRouteImport } from './routes/_authenticated/halaqoh'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedUjianIdRouteImport } from './routes/_authenticated/ujian.$id'
import { Route as AuthenticatedSantriIdRouteImport } from './routes/_authenticated/santri.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUjianRoute = AuthenticatedUjianRouteImport.update({
  id: '/ujian',
  path: '/ujian',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasmiRoute = AuthenticatedTasmiRouteImport.update({
  id: '/tasmi',
  path: '/tasmi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetoranRoute = AuthenticatedSetoranRouteImport.update({
  id: '/setoran',
  path: '/setoran',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSantriRoute = AuthenticatedSantriRouteImport.update({
  id: '/santri',
  path: '/santri',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPengaturanRoute = AuthenticatedPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaporanHarianRoute =
  AuthenticatedLaporanHarianRouteImport.update({
    id: '/laporan-harian',
    path: '/laporan-harian',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLaporanRoute = AuthenticatedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHalaqohRoute = AuthenticatedHalaqohRouteImport.update({
  id: '/halaqoh',
  path: '/halaqoh',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedUjianIdRoute = AuthenticatedUjianIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedUjianRoute,
} as any)
const AuthenticatedSantriIdRoute = AuthenticatedSantriIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSantriRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/halaqoh': typeof AuthenticatedHalaqohRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/laporan-harian': typeof AuthenticatedLaporanHarianRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/santri': typeof AuthenticatedSantriRouteWithChildren
  '/setoran': typeof AuthenticatedSetoranRoute
  '/tasmi': typeof AuthenticatedTasmiRoute
  '/ujian': typeof AuthenticatedUjianRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/santri/$id': typeof AuthenticatedSantriIdRoute
  '/ujian/$id': typeof AuthenticatedUjianIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/halaqoh': typeof AuthenticatedHalaqohRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/laporan-harian': typeof AuthenticatedLaporanHarianRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/santri': typeof AuthenticatedSantriRouteWithChildren
  '/setoran': typeof AuthenticatedSetoranRoute
  '/tasmi': typeof AuthenticatedTasmiRoute
  '/ujian': typeof AuthenticatedUjianRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/santri/$id': typeof AuthenticatedSantriIdRoute
  '/ujian/$id': typeof AuthenticatedUjianIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/halaqoh': typeof AuthenticatedHalaqohRoute
  '/_authenticated/laporan': typeof AuthenticatedLaporanRoute
  '/_authenticated/laporan-harian': typeof AuthenticatedLaporanHarianRoute
  '/_authenticated/pengaturan': typeof AuthenticatedPengaturanRoute
  '/_authenticated/santri': typeof AuthenticatedSantriRouteWithChildren
  '/_authenticated/setoran': typeof AuthenticatedSetoranRoute
  '/_authenticated/tasmi': typeof AuthenticatedTasmiRoute
  '/_authenticated/ujian': typeof AuthenticatedUjianRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/santri/$id': typeof AuthenticatedSantriIdRoute
  '/_authenticated/ujian/$id': typeof AuthenticatedUjianIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/halaqoh'
    | '/laporan'
    | '/laporan-harian'
    | '/pengaturan'
    | '/santri'
    | '/setoran'
    | '/tasmi'
    | '/ujian'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/santri/$id'
    | '/ujian/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/halaqoh'
    | '/laporan'
    | '/laporan-harian'
    | '/pengaturan'
    | '/santri'
    | '/setoran'
    | '/tasmi'
    | '/ujian'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/santri/$id'
    | '/ujian/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/dashboard'
    | '/_authenticated/halaqoh'
    | '/_authenticated/laporan'
    | '/_authenticated/laporan-harian'
    | '/_authenticated/pengaturan'
    | '/_authenticated/santri'
    | '/_authenticated/setoran'
    | '/_authenticated/tasmi'
    | '/_authenticated/ujian'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/santri/$id'
    | '/_authenticated/ujian/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ujian': {
      id: '/_authenticated/ujian'
      path: '/ujian'
      fullPath: '/ujian'
      preLoaderRoute: typeof AuthenticatedUjianRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasmi': {
      id: '/_authenticated/tasmi'
      path: '/tasmi'
      fullPath: '/tasmi'
      preLoaderRoute: typeof AuthenticatedTasmiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setoran': {
      id: '/_authenticated/setoran'
      path: '/setoran'
      fullPath: '/setoran'
      preLoaderRoute: typeof AuthenticatedSetoranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/santri': {
      id: '/_authenticated/santri'
      path: '/santri'
      fullPath: '/santri'
      preLoaderRoute: typeof AuthenticatedSantriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengaturan': {
      id: '/_authenticated/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AuthenticatedPengaturanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan-harian': {
      id: '/_authenticated/laporan-harian'
      path: '/laporan-harian'
      fullPath: '/laporan-harian'
      preLoaderRoute: typeof AuthenticatedLaporanHarianRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan': {
      id: '/_authenticated/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthenticatedLaporanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/halaqoh': {
      id: '/_authenticated/halaqoh'
      path: '/halaqoh'
      fullPath: '/halaqoh'
      preLoaderRoute: typeof AuthenticatedHalaqohRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ujian/$id': {
      id: '/_authenticated/ujian/$id'
      path: '/$id'
      fullPath: '/ujian/$id'
      preLoaderRoute: typeof AuthenticatedUjianIdRouteImport
      parentRoute: typeof AuthenticatedUjianRoute
    }
    '/_authenticated/santri/$id': {
      id: '/_authenticated/santri/$id'
      path: '/$id'
      fullPath: '/santri/$id'
      preLoaderRoute: typeof AuthenticatedSantriIdRouteImport
      parentRoute: typeof AuthenticatedSantriRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSantriRouteChildren {
  AuthenticatedSantriIdRoute: typeof AuthenticatedSantriIdRoute
}

const AuthenticatedSantriRouteChildren: AuthenticatedSantriRouteChildren = {
  AuthenticatedSantriIdRoute: AuthenticatedSantriIdRoute,
}

const AuthenticatedSantriRouteWithChildren =
  AuthenticatedSantriRoute._addFileChildren(AuthenticatedSantriRouteChildren)

interface AuthenticatedUjianRouteChildren {
  AuthenticatedUjianIdRoute: typeof AuthenticatedUjianIdRoute
}

const AuthenticatedUjianRouteChildren: AuthenticatedUjianRouteChildren = {
  AuthenticatedUjianIdRoute: AuthenticatedUjianIdRoute,
}

const AuthenticatedUjianRouteWithChildren =
  AuthenticatedUjianRoute._addFileChildren(AuthenticatedUjianRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHalaqohRoute: typeof AuthenticatedHalaqohRoute
  AuthenticatedLaporanRoute: typeof AuthenticatedLaporanRoute
  AuthenticatedLaporanHarianRoute: typeof AuthenticatedLaporanHarianRoute
  AuthenticatedPengaturanRoute: typeof AuthenticatedPengaturanRoute
  AuthenticatedSantriRoute: typeof AuthenticatedSantriRouteWithChildren
  AuthenticatedSetoranRoute: typeof AuthenticatedSetoranRoute
  AuthenticatedTasmiRoute: typeof AuthenticatedTasmiRoute
  AuthenticatedUjianRoute: typeof AuthenticatedUjianRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHalaqohRoute: AuthenticatedHalaqohRoute,
  AuthenticatedLaporanRoute: AuthenticatedLaporanRoute,
  AuthenticatedLaporanHarianRoute: AuthenticatedLaporanHarianRoute,
  AuthenticatedPengaturanRoute: AuthenticatedPengaturanRoute,
  AuthenticatedSantriRoute: AuthenticatedSantriRouteWithChildren,
  AuthenticatedSetoranRoute: AuthenticatedSetoranRoute,
  AuthenticatedTasmiRoute: AuthenticatedTasmiRoute,
  AuthenticatedUjianRoute: AuthenticatedUjianRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
